# Generated by Django 5.1.1 on 2024-09-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inventario', models.CharField(max_length=10, unique=True)),
                ('denominacao', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Senai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1500)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nif', models.CharField(max_length=8)),
                ('sala', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
